### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by solitudealma** [liaohui5/dotfiles#1]
这个仓库的nvim去年是不是不是用的lazyvim，是不是把仓库删了

**Comment by liaohui5** [comment]
> 这个仓库的nvim去年是不是不是用的lazyvim，是不是把仓库删了
是的，重构了几次了，最开始自己手写配置，然后用 lazyVIM+手动配置插件，然后lazyVIM更新了 extra 模块， 我就又重新重构了一次插件配置的文件结构
